name: SSH Connection Test

on:
  workflow_dispatch:  # 手動実行を可能にする

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail

      - name: Test SSH Connection
        run: |
          # SSH接続テスト（詳細なデバッグ情報付き）
          ssh -v ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo SSH接続成功！サーバー情報: \$(uname -a)"
          
      - name: Test rsync Command
        run: |
          # rsyncがインストールされているか確認
          which rsync || (sudo apt-get update && sudo apt-get install -y rsync)
          
          # 空のテストディレクトリを作成
          mkdir -p test_deploy
          touch test_deploy/test_file.txt
          
          # rsyncコマンドのテスト（実際のファイルは送信しない、--dry-run使用）
          rsync -avz --dry-run -e "ssh -v" \
            test_deploy/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/tmp/test_deploy/
          
          echo "rsyncのテスト成功！"
